1,Afghanistan
2,Albania
3,Algeria
5,Andorra
6,Angola
7,Anguilla
8,Antarctica
9,Antigua & Barbuda
10,Argentina
11,Armenia
12,Aruba
13,Australia
14,Austria
15,Azerbaijan
16,Bahamas
17,Bahrain
18,Bangladesh
19,Barbados
20,Belarus
21,Belgium
22,Belize
23,Benin
24,Bermuda
25,Bhutan
26,Bolivia
27,Bosnia-Herzegovina
28,Botswana
30,Brazil
220,British Virgin Islands
31,Brunei
32,Bulgaria
33,Burkina Faso
34,Burundi
35,Cambodia
36,Cameroon
37,Canada
38,Cape Verde
39,Cayman Islands
40,Central African Republic
41,Chad
230,Channel Islands
42,Chile
43,China
46,Colombia
47,Comoros
49,Cook Islands
50,Costa Rica
51,Croatia
52,Cuba
242,Curaçao
53,Cyprus
54,Czech Republic
231,Democratic Republic of the Congo
55,Denmark
56,Djibouti
57,Dominica
58,Dominican Republic
60,Ecuador
61,Egypt
62,El Salvador
63,Equatorial Guinea
232,Eritrea
64,Estonia
65,Ethiopia
66,Falkland Islands
68,Fiji
69,Finland
71,France
72,French Guiana
233,French Polynesia
73,Gabon
74,Gambia
75,Georgia
76,Germany
77,Ghana
78,Gibraltar
79,Greece
80,Greenland
81,Grenada
82,Guadeloupe
84,Guatemala
85,Guinea
86,Guinea-Bissau
87,Guyana
88,Haiti
89,Honduras
90,Hong Kong
91,Hungary
92,Iceland
93,India
94,Indonesia
95,Iran
96,Iraq
97,Ireland
239,Isle of Man
98,Israel
99,Italy
100,Ivory Coast
101,Jamaica
102,Japan
103,Jordan
104,Kazakhstan
105,Kenya
106,Kiribati
241,Kosovo
107,Kuwait
108,Kyrgyzstan
109,Laos
110,Latvia
111,Lebanon
112,Lesotho
113,Liberia
114,Libya
115,Liechtenstein
116,Lithuania
117,Luxembourg
118,Macau
119,Macedonia
120,Madagascar
121,Malawi
122,Malaysia
123,Maldives
124,Mali
125,Malta
126,Marshall Islands
127,Martinique
128,Mauritania
129,Mauritius
131,Mexico
133,Moldova
134,Monaco
135,Mongolia
238,Montenegro
136,Montserrat
137,Morocco
138,Mozambique
139,Myanmar
140,Namibia
141,Nauru
142,Nepal
143,Netherlands
144,Netherlands Antilles
146,New Caledonia
147,New Zealand
148,Nicaragua
149,Niger
150,Nigeria
153,North Korea
154,Norway
155,Oman
156,Pakistan
240,Palestinian Authority
158,Panama
159,Papua New Guinea
160,Paraguay
161,Peru
162,Philippines
164,Poland
166,Portugal
168,Qatar
48,Republic of the Congo
169,Reunion
170,Romania
171,Russia
172,Rwanda
234,Saint Kitts & Nevis
174,Saint Lucia
175,Saint Vincent & Grenadines
176,Samoa
177,San Marino
178,Saudi Arabia
179,Senegal
236,Serbia
180,Seychelles
181,Sierra Leone
182,Singapore
183,Slovakia
184,Slovenia
185,Solomon Islands
186,Somalia
187,South Africa
188,South Korea
189,Spain
190,Sri Lanka
191,Sudan
192,Suriname
193,Swaziland
194,Sweden
195,Switzerland
196,Syria
198,Taiwan
197,Tajikistan
199,Tanzania
200,Thailand
237,Timor-Leste
201,Togo
203,Tonga
204,Trinidad & Tobago
205,Tunisia
206,Turkey
207,Turkmenistan
235,Turks & Caicos Islands
208,Tuvalu
209,Uganda
210,Ukraine
211,United Arab Emirates
212,United Kingdom
213,United States
214,Uruguay
215,Uzbekistan
216,Vanuatu
217,Vatican City
218,Venezuela
219,Vietnam
224,Yemen
225,Yugoslavia
227,Zambia
228,Zimbabwe